# Generated by Django 6.0.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaAtrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ikona', models.CharField(blank=True, help_text='Nazwa ikony np. z Font Awesome: fa-hiking', max_length=50)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoria atrakcji',
                'verbose_name_plural': 'Kategorie atrakcji',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='Atrakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('odleglosc_km', models.DecimalField(decimal_places=1, help_text='Odległość od pensjonatu w km', max_digits=5)),
                ('czas_dojazdu_min', models.PositiveIntegerField(blank=True, help_text='Szacowany czas dojazdu samochodem w minutach', null=True)),
                ('trudnosc', models.CharField(blank=True, choices=[('latwa', 'Łatwa'), ('srednia', 'Średnia'), ('trudna', 'Trudna')], help_text='Dotyczy szlaków i tras', max_length=10)),
                ('dlugosc_trasy_km', models.DecimalField(blank=True, decimal_places=1, help_text='Długość trasy w km (dla szlaków)', max_digits=5, null=True)),
                ('link_zewnetrzny', models.URLField(blank=True, help_text='Link do strony atrakcji, mapy, rezerwacji itp.')),
                ('aktywna', models.BooleanField(default=True)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atrakcje', to='atrakcje.kategoriaatrakcji')),
            ],
            options={
                'verbose_name': 'Atrakcja',
                'verbose_name_plural': 'Atrakcje',
                'ordering': ['kategoria', 'kolejnosc', 'odleglosc_km'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieAtrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='atrakcje/')),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('okladka', models.BooleanField(default=False, help_text='Zdjęcie główne wyświetlane na liście atrakcji')),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='atrakcje.atrakcja')),
            ],
            options={
                'verbose_name': 'Zdjęcie atrakcji',
                'verbose_name_plural': 'Zdjęcia atrakcji',
                'ordering': ['-okladka', 'kolejnosc'],
            },
        ),
    ]
