# Generated by Django 6.0.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoria menu',
                'verbose_name_plural': 'Kategorie menu',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='KategoriaWyrobu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoria wyrobu',
                'verbose_name_plural': 'Kategorie wyrobów',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='SalaRestauracyjna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('liczba_miejsc', models.PositiveIntegerField()),
                ('dostepna_na_imprezy', models.BooleanField(default=False, help_text='Czy sala jest dostępna na imprezy okolicznościowe?')),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sala restauracyjna',
                'verbose_name_plural': 'Sale restauracyjne',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('widoczne', models.BooleanField(default=True, help_text='Odznacz żeby ukryć danie z menu bez usuwania')),
                ('wegetarianskie', models.BooleanField(default=False)),
                ('wegańskie', models.BooleanField(default=False)),
                ('bezglutenowe', models.BooleanField(default=False)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dania', to='restauracja.kategoriamenu')),
            ],
            options={
                'verbose_name': 'Danie',
                'verbose_name_plural': 'Dania',
                'ordering': ['kategoria', 'kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='Wyrob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('sklad', models.TextField(blank=True, help_text='Skład produktu')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jednostka', models.CharField(choices=[('kg', 'za kilogram'), ('szt', 'za sztukę'), ('opak', 'za opakowanie')], default='kg', max_length=10)),
                ('dostepny', models.BooleanField(default=True, help_text='Odznacz jeśli wyrób jest chwilowo niedostępny')),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wyroby', to='restauracja.kategoriawyrobu')),
            ],
            options={
                'verbose_name': 'Wyrób własny',
                'verbose_name_plural': 'Wyroby własne',
                'ordering': ['kategoria', 'kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieSali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='sale/')),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('okladka', models.BooleanField(default=False, help_text='Zdjęcie główne wyświetlane na liście sal')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='restauracja.salarestauracyjna')),
            ],
            options={
                'verbose_name': 'Zdjęcie sali',
                'verbose_name_plural': 'Zdjęcia sal',
                'ordering': ['-okladka', 'kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieWyrobu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='wyroby/')),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('okladka', models.BooleanField(default=False)),
                ('wyrob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='restauracja.wyrob')),
            ],
            options={
                'verbose_name': 'Zdjęcie wyrobu',
                'verbose_name_plural': 'Zdjęcia wyrobów',
                'ordering': ['-okladka', 'kolejnosc'],
            },
        ),
    ]
