# Generated by Django 6.0.3 on 2026-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GodzinyOtwarcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], unique=True)),
                ('godzina_od', models.TimeField(blank=True, null=True)),
                ('godzina_do', models.TimeField(blank=True, null=True)),
                ('zamkniete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Godziny otwarcia',
                'verbose_name_plural': 'Godziny otwarcia',
                'ordering': ['dzien'],
            },
        ),
    ]
