# Generated by Django 6.0.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impreza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cena_od', models.DecimalField(blank=True, decimal_places=2, help_text='Cena orientacyjna od', max_digits=8, null=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='imprezy/')),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impreza okolicznościowa',
                'verbose_name_plural': 'Imprezy okolicznościowe',
            },
        ),
        migrations.CreateModel(
            name='SezonCenowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rodzaj', models.CharField(choices=[('lato', 'Lato'), ('zima', 'Zima'), ('swieta', 'Święta'), ('standard', 'Standard')], default='standard', max_length=20)),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('aktywny', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sezon cenowy',
                'verbose_name_plural': 'Sezony cenowe',
                'ordering': ['data_od'],
            },
        ),
        migrations.CreateModel(
            name='TypPokoju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('liczba_osob', models.PositiveIntegerField()),
                ('powierzchnia', models.DecimalField(blank=True, decimal_places=2, help_text='Powierzchnia w m²', max_digits=5, null=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Typ pokoju',
                'verbose_name_plural': 'Typy pokojów',
                'ordering': ['liczba_osob'],
            },
        ),
        migrations.CreateModel(
            name='UdogodnieniePokoju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ikona', models.CharField(blank=True, help_text='Nazwa ikony np. z Font Awesome: fa-wifi', max_length=50)),
            ],
            options={
                'verbose_name': 'Udogodnienie',
                'verbose_name_plural': 'Udogodnienia',
            },
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=10, unique=True)),
                ('opis_dodatkowy', models.TextField(blank=True, help_text='Opcjonalny opis szczegółowy dla tego konkretnego pokoju')),
                ('dostepny', models.BooleanField(default=True)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokoje', to='oferta.typpokoju')),
                ('udogodnienia', models.ManyToManyField(blank=True, related_name='pokoje', to='oferta.udogodnieniepokoju')),
            ],
            options={
                'verbose_name': 'Pokój',
                'verbose_name_plural': 'Pokoje',
                'ordering': ['numer'],
            },
        ),
        migrations.CreateModel(
            name='ZdjeciePokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='pokoje/')),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('okladka', models.BooleanField(default=False, help_text='Zdjęcie główne wyświetlane na liście pokojów')),
                ('typ_pokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='oferta.typpokoju')),
            ],
            options={
                'verbose_name': 'Zdjęcie pokoju',
                'verbose_name_plural': 'Zdjęcia pokojów',
                'ordering': ['-okladka', 'kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='CenaPokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_za_noc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sezon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceny', to='oferta.sezoncenowy')),
                ('typ_pokoju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceny', to='oferta.typpokoju')),
            ],
            options={
                'verbose_name': 'Cena pokoju',
                'verbose_name_plural': 'Ceny pokojów',
                'unique_together': {('typ_pokoju', 'sezon')},
            },
        ),
    ]
