# Generated by Django 6.0.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SekcjaGalerii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('pokoje', 'Pokoje'), ('podworze', 'Podwórze'), ('pensjonat', 'Pensjonat'), ('okolice', 'Okolice'), ('restauracja', 'Restauracja')], max_length=20, unique=True)),
                ('opis', models.CharField(blank=True, max_length=300)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywna', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sekcja galerii',
                'verbose_name_plural': 'Sekcje galerii',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='galeria/%Y/%m/')),
                ('tytul', models.CharField(blank=True, max_length=200)),
                ('opis', models.CharField(blank=True, max_length=500)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywne', models.BooleanField(default=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('wyroznienie', models.BooleanField(default=False, help_text='Wyróżnione zdjęcie pokazywane na stronie głównej sekcji')),
                ('sekcja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zdjecia', to='galeria.sekcjagalerii')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
                'ordering': ['-wyroznienie', 'kolejnosc', '-data_dodania'],
            },
        ),
    ]
