# Generated by Django 6.0.2 on 2026-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('temat', models.CharField(max_length=200)),
                ('wiadomosc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('przeczytana', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-data_wyslania'],
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_wygasniecia', models.DateField(blank=True, help_text='Zostaw puste jeśli ogłoszenie ma być stałe', null=True)),
                ('aktywne', models.BooleanField(default=True)),
                ('wazne', models.BooleanField(default=False, help_text='Wyróżnione ogłoszenie na górze listy')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
                'ordering': ['-wazne', '-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='ONas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='o_nas/')),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywne', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sekcja O nas',
                'verbose_name_plural': 'Sekcje O nas',
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='UstawieniaStrony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pensjonatu', models.CharField(max_length=200)),
                ('opis_hero', models.TextField(help_text='Tekst na stronie głównej')),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.TextField()),
                ('google_maps_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Ustawienia strony',
                'verbose_name_plural': 'Ustawienia strony',
            },
        ),
        migrations.CreateModel(
            name='ZdjecieHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='hero/')),
                ('tytul', models.CharField(blank=True, max_length=200)),
                ('podtytul', models.CharField(blank=True, max_length=300)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('aktywne', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zdjęcie hero',
                'verbose_name_plural': 'Zdjęcia hero',
                'ordering': ['kolejnosc'],
            },
        ),
    ]
